# Spam Email Detection using NLP & Naive Byes Algorithm 

### ✅ Business Problem Statement

In today's digital communication landscape, spam emails pose a significant threat to productivity, privacy, and security. 

Filtering spam accurately helps organizations reduce phishing attacks, unnecessary data overload, and employee distractions. 

The goal of this case study is to build a machine learning model that can classify incoming emails as spam or not spam (ham) 

using the Naive Bayes algorithm and natural language processing (NLP) techniques.

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB # For naive bayes algorithm
from sklearn.metrics import accuracy_score,classification_report

### Step 1 : Load dataset

In [2]:
data = pd.read_csv("spam.csv",encoding="latin-1")
#📌 You need encoding="latin-1" because the file includes special characters

# that can't be correctly interpreted with the default utf-8.

# It tells pandas: “Read this file using a looser standard that won't crash on unknown characters.”

In [3]:
data.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN


In [5]:
data.tail()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
5567,spam,This is the 2nd time we have tried 2 contact u...,NaN,NaN,NaN
5568,ham,Will Ì_ b going to esplanade fr home?,NaN,NaN,NaN
5569,ham,"Pity, * was in mood for that. So...any other s...",NaN,NaN,NaN
5570,ham,The guy did some bitching but I acted like i'd...,NaN,NaN,NaN
5571,ham,Rofl. Its true to its name,NaN,NaN,NaN


In [6]:
data.shape

(5572, 5)

In [7]:
data = data[["v1","v2"]]
data.columns = ["label","text"]

In [8]:
data.head()

,label,text
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."


In [9]:
data.head(10)

,label,text
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."
5,spam,FreeMsg Hey there darling it's been 3 week's n...
6,ham,Even my brother is not like to speak with me. ...
7,ham,As per your request 'Melle Melle (Oru Minnamin...
8,spam,WINNER!! As a valued network customer you have...
9,spam,Had your mobile 11 months or more? U R entitle...


In [10]:
data.tail(10)

,label,text
5562,ham,Ok lor... Sony ericsson salesman... I ask shuh...
5563,ham,Ard 6 like dat lor.
5564,ham,Why don't you wait 'til at least wednesday to ...
5565,ham,Huh y lei...
5566,spam,REMINDER FROM O2: To get 2.50 pounds free call...
5567,spam,This is the 2nd time we have tried 2 contact u...
5568,ham,Will Ì_ b going to esplanade fr home?
5569,ham,"Pity, * was in mood for that. So...any other s..."
5570,ham,The guy did some bitching but I acted like i'd...
5571,ham,Rofl. Its true to its name


### Step 2 : Preprocessing

In [11]:
data["label"] = data["label"].map({"ham" : 0,"spam" : 1})
#Converting text labels to binary format (0 = not spam, 1 = spam) for model training.

C:\Users\aman kumar\AppData\Local\Temp\ipykernel_29608\3679069523.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["label"] = data["label"].map({"ham" : 0,"spam" : 1})


In [12]:
data.head(10)

,label,text
0,0,"Go until jurong point, crazy.. Available only ..."
1,0,Ok lar... Joking wif u oni...
2,1,Free entry in 2 a wkly comp to win FA Cup fina...
3,0,U dun say so early hor... U c already then say...
4,0,"Nah I don't think he goes to usf, he lives aro..."
5,1,FreeMsg Hey there darling it's been 3 week's n...
6,0,Even my brother is not like to speak with me. ...
7,0,As per your request 'Melle Melle (Oru Minnamin...
8,1,WINNER!! As a valued network customer you have...
9,1,Had your mobile 11 months or more? U R entitle...


### Step 3 : Feature Extraction 

In [13]:
vectorizer = TfidfVectorizer(stop_words="english")

# Getting a list of common stopwords (e.g., "the","is") to remove later.
x =  vectorizer.fit_transform(data["text"])
y = data["label"]

In [14]:
x

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 43478 stored elements and shape (5572, 8404)>

In [15]:
y[0:10]

0    0
1    0
2    1
3    0
4    0
5    1
6    0
7    0
8    1
9    1
Name: label, dtype: int64

In [16]:
x[10:15].toarray()

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.20981775, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.21993545, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]], shape=(5, 8404))

### Step 4 : Train_test_split

In [17]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.20,random_state=42)

In [18]:
x_train.shape,y_train.shape

((4457, 8404), (4457,))

In [19]:
x_test.shape,y_test.shape

((1115, 8404), (1115,))

### Step 5 : Train model (Naive Bayes)

In [20]:
model = MultinomialNB()
model.fit(x_train,y_train)

# trainning a multinomial naive bayes classifier on the text features

,alpha,1.0
,force_alpha,True
,fit_prior,True
,class_prior,None


### Step 6 : Evaluate models

In [21]:
y_pred = model.predict(x_test)
y_pred[0:10]

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [22]:
print("Accuracy :",accuracy_score(y_test,y_pred))

Accuracy : 0.968609865470852


In [23]:
print("Classification Report :\n",classification_report(y_test,y_pred))

Classification Report :
               precision    recall  f1-score   support

           0       0.96      1.00      0.98       965
           1       1.00      0.77      0.87       150

    accuracy                           0.97      1115
   macro avg       0.98      0.88      0.93      1115
weighted avg       0.97      0.97      0.97      1115



In [24]:
data["label"].value_counts()

label
0    4825
1     747
Name: count, dtype: int64

### Observation:

Excellent Performance on Class 0 (Negative Sentiment):

The model achieves near-perfect precision (0.96) and recall (1.00) for class 0, indicating it reliably identifies negative reviews with minimal false positives/negatives.

Class Imbalance Impact on Class 1 (Positive Sentiment):


While precision is perfect (1.00) for class 1, recall drops to 0.77, suggesting the model misses 23% of positive cases - likely due to the smaller sample size (150 vs 965). The high weighted avg (0.97) confirms overall strong performance despite this imbalance.